const formulaData = [
    { storhet: "massa", bStorhet: "m", enhet: "kilogram", bEnhet: "kg" },
    { storhet: "volym", bStorhet: "V", enhet: "kubikmeter", bEnhet: "m3" },
    { storhet: "densitet", bStorhet: "ρ", enhet: "kilogram/kubikmeter", bEnhet: "kg/m3" },
    { storhet: "kraft", bStorhet: "F", enhet: "newton", bEnhet: "N" },
    { storhet: "hastighet", bStorhet: "v", enhet: "meter/sekund", bEnhet: "m/s" },
    { storhet: "sträcka", bStorhet: "s", enhet: "meter", bEnhet: "m" },
    { storhet: "tid", bStorhet: "t", enhet: "sekund", bEnhet: "s" },
    { storhet: "acceleration", bStorhet: "a", enhet: "meter/sekundkvadrat", bEnhet: "m/s2" },
    { storhet: "energi", bStorhet: "E", enhet: "joule", bEnhet: "J" },
    { storhet: "arbete", bStorhet: "W", enhet: "joule", bEnhet: "J" },
    { storhet: "effekt", bStorhet: "P", enhet: "watt", bEnhet: "W" },
    { storhet: "kinetisk energi", bStorhet: "EK", enhet: "joule", bEnhet: "J" },
    { storhet: "potentiell energi", bStorhet: "EP", enhet: "joule", bEnhet: "J" },
    { storhet: "verkningsgrad", bStorhet: "h", enhet: "-", bEnhet: "-" },
    { storhet: "rörelsemängd", bStorhet: "p", enhet: "kilogrammeter/sekund", bEnhet: "kgm/s" },
    { storhet: "impuls", bStorhet: "I", enhet: "newtonsekund", bEnhet: "Ns" },
    { storhet: "tryck", bStorhet: "p", enhet: "pascal", bEnhet: "Pa" },
    { storhet: "lyftkraft", bStorhet: "FL", enhet: "newton", bEnhet: "N" },
    { storhet: "temperatur", bStorhet: "T", enhet: "kelvin", bEnhet: "K" },
    { storhet: "värmeenergi", bStorhet: "Q", enhet: "joule", bEnhet: "J" },
    { storhet: "specifik värmekapacitet", bStorhet: "c", enhet: "joule/(kilogramkelvin)", bEnhet: "J/(kgK)" },
    { storhet: "värmekapacitet", bStorhet: "C", enhet: "joule/kilogram", bEnhet: "J/kg" },
    { storhet: "specifik smältentalpi", bStorhet: "cs", enhet: "joule/kilogram", bEnhet: "J/kg" },
    { storhet: "specifik ångbildningsentalpi", bStorhet: "cå", enhet: "joule/kilogram", bEnhet: "J/kg" },
    { storhet: "laddning", bStorhet: "Q", enhet: "coulomb", bEnhet: "C" },
    { storhet: "elektrisk fältstyrka", bStorhet: "[Ekvation]", enhet: "newton/coulomb = volt/meter", bEnhet: "N/C = V/m" },
    { storhet: "ström", bStorhet: "I", enhet: "ampere", bEnhet: "A" },
    { storhet: "spänning", bStorhet: "U", enhet: "volt", bEnhet: "V" },
    { storhet: "resistans", bStorhet: "R", enhet: "ohm", bEnhet: "W" },
    { storhet: "aktivitet", bStorhet: "A", enhet: "becquerel", bEnhet: "Bq" },
    { storhet: "absorberad dos", bStorhet: "D", enhet: "gray", bEnhet: "Gy" },
    { storhet: "ekvivalent dos", bStorhet: "H", enhet: "sievert", bEnhet: "Sv" }
];