const formulaData = [
    { storhet: "massa", bStorhet: "m", enhet: "kilogram", bEnhet: "kg", level: 1 },
    { storhet: "volym", bStorhet: "V", enhet: "kubikmeter", bEnhet: "m³", level: 1 },
    { storhet: "densitet", bStorhet: "ρ", enhet: "kilogram/kubikmeter", bEnhet: "kg/m³", level: 1 },
    { storhet: "kraft", bStorhet: "F", enhet: "newton", bEnhet: "N", level: 1 },
    { storhet: "hastighet", bStorhet: "v", enhet: "meter/sekund", bEnhet: "m/s", level: 2 },
    { storhet: "sträcka", bStorhet: "s", enhet: "meter", bEnhet: "m", level: 2 },
    { storhet: "tid", bStorhet: "t", enhet: "sekund", bEnhet: "s", level: 2 },
    { storhet: "acceleration", bStorhet: "a", enhet: "meter/sekundkvadrat", bEnhet: "m/s²", level: 2 },
    { storhet: "energi", bStorhet: "E", enhet: "joule", bEnhet: "J", level: 3 },
    { storhet: "arbete", bStorhet: "W", enhet: "joule", bEnhet: "J", level: 3 },
    { storhet: "effekt", bStorhet: "P", enhet: "watt", bEnhet: "W", level: 3 },
    { storhet: "kinetisk energi", bStorhet: "Eₖ", enhet: "joule", bEnhet: "J", level: 3 },
    { storhet: "potentiell energi", bStorhet: "Eₚ", enhet: "joule", bEnhet: "J", level: 3 },
    { storhet: "verkningsgrad", bStorhet: "η", enhet: "-", bEnhet: "-", level: 3 },
    { storhet: "rörelsemängd", bStorhet: "p", enhet: "kilogrammeter/sekund", bEnhet: "kgm/s", level: 4 },
    { storhet: "impuls", bStorhet: "I", enhet: "newtonsekund", bEnhet: "Ns", level: 4 },
    { storhet: "tryck", bStorhet: "p", enhet: "pascal", bEnhet: "Pa", level: 5 },
    { storhet: "lyftkraft", bStorhet: "Fₗ", enhet: "newton", bEnhet: "N", level: 5 },
    { storhet: "temperatur", bStorhet: "T", enhet: "kelvin", bEnhet: "K", level: 5 },
    { storhet: "värmeenergi", bStorhet: "Q", enhet: "joule", bEnhet: "J", level: 5 },
    { storhet: "specifik värmekapacitet", bStorhet: "c", enhet: "joule/(kilogramkelvin)", bEnhet: "J/(kgK)", level: 5 },
    { storhet: "värmekapacitet", bStorhet: "C", enhet: "joule/kilogram", bEnhet: "J/kg", level: 5 },
    { storhet: "specifik smältentalpi", bStorhet: "cₛ", enhet: "joule/kilogram", bEnhet: "J/kg", level: 5 },
    { storhet: "specifik ångbildningsentalpi", bStorhet: "cå", enhet: "joule/kilogram", bEnhet: "J/kg", level: 5 },
    { storhet: "laddning", bStorhet: "Q", enhet: "coulomb", bEnhet: "C", level: 6 },
    { storhet: "elektrisk fältstyrka", bStorhet: "𝔼", enhet: "N/C = V/m", bEnhet: "N/C", level: 6 },
    { storhet: "ström", bStorhet: "I", enhet: "ampere", bEnhet: "A", level: 6 },
    { storhet: "spänning", bStorhet: "U", enhet: "volt", bEnhet: "V", level: 6 },
    { storhet: "resistans", bStorhet: "R", enhet: "ohm", bEnhet: "Ω", level: 6 },
    { storhet: "aktivitet", bStorhet: "A", enhet: "becquerel", bEnhet: "Bq", level: 7 },
    { storhet: "absorberad dos", bStorhet: "D", enhet: "gray", bEnhet: "Gy", level: 7 },
    { storhet: "ekvivalent dos", bStorhet: "H", enhet: "sievert", bEnhet: "Sv", level: 7 }
];